### ISSUE TITLE
Module importing does not work with `guix reconfigure`

### ISSUE THREAD

**Issue by JohnAZoidberg** [alezost/guix-config#1]
I'm new to GuixSD (coming from NixOS) and I was looking at your repo for inspiration. However I cannot figure out how to write modules.

When I try to build your main configuration it can, apparently, find the module but not the variable declared inside. (This is after I remove the missing modules for `(al places)`, `(al files)` and `(al utils)`.)

```
$ guix system build system-config/os-main.scm --dry-run
error: my-package: unbound variable
hint: Did you forget `(use-modules (al guix utils))'?
```

`(use-modules (al guix utils))` is clearly used in `system-config/os-main.scm` so where does the error come from?

I had expanded my env using `export GUILE_LOAD_PATH=$(pwd/modules):$GUILE_LOAD_PATH`

**Comment by alezost** [comment]
Hello, as I mentioned in README, I use my [guile modules](https://github.com/alezost/guile-config/tree/master/modules/al).

These modules are required for the code from this repository.  Also I add [modules](https://github.com/alezost/guix-config/tree/master/modules) directory to ` GUILE_LOAD_PATH`.

> I had expanded my env using `export GUILE_LOAD_PATH=$(pwd/modules):$GUILE_LOAD_PATH`

(If you really want to try my config) please, make sure both `modules` (from `guile-config` and `guix-config`) directories are added.

**Comment by JohnAZoidberg** [comment]
Thanks, now it works.
Seems like, whenever a module fails to evaluate, instead of showing the error, `guix reconfigure` shows `hint: Did you forget ...`.
